Mail API
noted-eip/accounts-service pull request #96
Opened 2023-03-07 03:04 UTC by maxime-dodin

#### Description

- mail API setup, 
- sendEmail Endpoint implementation with port smtp
- query to get emails from account_id list
- html template for generic and customisable mails, title and content are part of the request 

Fixes #95 

#### Changelog

- [BUGFIX]
- [ENHANCEMENT]
- [DOCS]
- ...

2023-03-09 04:35 UTC, gabriel654165 requested changes

2023-03-12 22:37 UTC, maxime-dodin commented on mailing.go
> +		TITLE:   in.Title,
Yeah, I will add the updated version when the new protorepo PR is merged

2023-03-12 22:39 UTC, maxime-dodin commented on mailing.go
> +func (srv *mailingAPI) SendEmail(ctx context.Context, in *mailingv1.SendEmailRequest) (*mailingv1.SendEmailResponse, error) {
I'm Ok with changing the name of the methods, i'm waiting for the protorepo for the updated names

2023-03-12 22:42 UTC, maxime-dodin commented on mailing.go
> +	r := NewRequest("noted.organisation@gmail.com", mails, in.Subject, in.MarkdownBody, srv.secret)
Hey, the front won't call SendEmails, it's an internal service in the back,

2023-03-19 22:22 UTC, merged